
    create table tb_apartamento (
        id_apartamento bigint generated by default as identity,
        data_liberacao date,
        data_reserva date,
        nome varchar(255),
        primary key (id_apartamento)
    );
    
    create table tb_funcionario (
        id_funcionario bigint generated by default as identity,
        cargo varchar(255),
        nome varchar(255),
        primary key (id_funcionario)
    );

    create table tb_hospede (
        id_hospede bigint generated by default as identity,
        cidade varchar(255),
        cpf varchar(255),
        data_nasc timestamp,
        email varchar(255),
        endereco varchar(255),
        estado varchar(255),
        nome varchar(255),
        numero integer not null,
        rg varchar(255),
        telefone integer not null,
        primary key (id_hospede)
    );

    create table tb_reserva (
        id_codigo bigint generated by default as identity,
        data_entrada date,
        data_saida date,
        status_reserva integer not null,
        id_apartamento bigint,
        id_hospede bigint,
        primary key (id_codigo)
    );

        alter table tb_reserva
           add constraint FK54e7ulpofe7227fusv1lngin6
           foreign key (id_apartamento)
           references tb_apartamento;

        alter table tb_reserva
           add constraint FKo1wxdh2otdxuxs78mcr99iik6
           foreign key (id_hospede)
           references tb_hospede;